# Generated by Django 3.1.5 on 2021-01-25 21:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None)),
            ],
        ),
    ]
