# Generated by Django 3.1.5 on 2021-01-25 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perlego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=list, size=None),
        ),
    ]
